[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projet_ceren_sylla"
version = "1.0.0"
description = "Application pour gérer les réservations de rooms"
authors = [{name = "CEREN/ SYLLA", email = "daoudesylla@gmail.com"}]
dependencies = [
    "tkcalendar",  # Widget calendrier pour tkinter
    "pytest==6.2.4",
    
]
[project.scripts]
lancer_application = "src.gui:main"

[tool.pytest.ini_options]
pythonpath = ["."]